# Generated by Django 5.1.15 on 2026-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='formation',
            field=models.CharField(choices=[('bureautique', 'Formation en bureautique'), ('maintenance', 'Formation en maintenance'), ('reseau', 'Formation en réseau'), ('initiation', 'Initiation en informatique')], default='initiation', max_length=50, verbose_name='Type de formation'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='session',
            field=models.CharField(choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], default='janvier', max_length=20, verbose_name='Session (mois)'),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
