# Generated by Django 5.0.3 on 2026-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apprenant_formation_apprenant_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant unique sans espaces ni caractères spéciaux', unique=True, verbose_name='Code / Identifiant (ex: dev-web, bureautique)')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet de la formation')),
                ('description', models.TextField(blank=True, verbose_name='Description de la formation')),
                ('est_active', models.BooleanField(default=True, verbose_name='Formation active (visible aux inscriptions)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formation',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='formation',
            field=models.CharField(default='initiation', max_length=50, verbose_name='Type de formation'),
        ),
    ]
