# Generated by Django 5.1.15 on 2026-09-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_formation_alter_apprenant_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='formation_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateurs', to='accounts.formation', verbose_name='Formation assignée'),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='is_formateur',
            field=models.BooleanField(default=False, verbose_name='Membreee= des formateurs'),
        ),
    ]
