# Generated by Django 5.0.3 on 2026-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apprenant_formation_assignee_apprenant_is_formateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='is_formateur',
            field=models.BooleanField(default=False, verbose_name='Membre formateur'),
        ),
    ]
