# Generated by Django 5.1.15 on 2026-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_apprenant_is_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil'),
        ),
    ]
