# Generated by Django 5.0.3 on 2026-08-31 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du devoir')),
                ('formation', models.CharField(choices=[('bureautique', 'Formation en bureautique'), ('maintenance', 'Formation en maintenance'), ('reseau', 'Formation en réseau'), ('initiation', 'Initiation en informatique')], max_length=50, verbose_name='Formation concernée')),
                ('description', models.TextField(blank=True, verbose_name='Description / consignes')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Devoir actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte de la question')),
                ('choix_a', models.CharField(max_length=300, verbose_name='Choix A')),
                ('choix_b', models.CharField(max_length=300, verbose_name='Choix B')),
                ('choix_c', models.CharField(max_length=300, verbose_name='Choix C')),
                ('choix_d', models.CharField(max_length=300, verbose_name='Choix D')),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Bonne réponse')),
                ('justification', models.TextField(verbose_name='Justification (pour la correction)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='devoirs.devoir')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(verbose_name='Note obtenue')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='devoirs.devoir')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-date_soumission'],
                'unique_together': {('apprenant', 'devoir')},
            },
        ),
        migrations.CreateModel(
            name='ReponseApprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_choisie', models.CharField(max_length=1)),
                ('est_correcte', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.question')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='devoirs.soumission')),
            ],
            options={
                'verbose_name': 'Réponse apprenant',
                'verbose_name_plural': 'Réponses apprenants',
            },
        ),
    ]
