# Generated by Django 5.0.3 on 2026-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='session',
            field=models.CharField(choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], default='janvier', max_length=20, verbose_name='Session du devoir'),
        ),
    ]
