# Generated by Django 5.1.15 on 2026-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0002_devoir_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='note',
            field=models.PositiveBigIntegerField(verbose_name='Note obtenue'),
        ),
    ]
