# Generated by Django 5.1.15 on 2026-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0003_alter_soumission_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='formation',
            field=models.CharField(default='initation en informatique', max_length=50, verbose_name='Formation concernée'),
        ),
    ]
