# Generated by Django 5.0.3 on 2026-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0004_alter_devoir_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='formation',
            field=models.CharField(default='initiation', max_length=50, verbose_name='Formation concernée'),
        ),
    ]
