# Generated by Django 5.1.15 on 2026-09-16 12:12

import devoirs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0005_alter_devoir_formation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourcePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la ressource')),
                ('description', models.TextField(blank=True, verbose_name='Description / résumé du cours')),
                ('fichier', models.FileField(upload_to=devoirs.models.ressource_upload_path, verbose_name='Fichier (PDF ou vidéo)')),
                ('type_fichier', models.CharField(choices=[('pdf', 'Document PDF'), ('video', 'Vidéo de cours')], default='pdf', max_length=10, verbose_name='Type de ressource')),
                ('formation', models.CharField(max_length=50, verbose_name='Formation concernée')),
                ('session', models.CharField(choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], default='janvier', max_length=20, verbose_name='Session concernée')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible pour les apprenants')),
                ('formateur', models.ForeignKey(blank=True, limit_choices_to={'is_formateur': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_deposees', to=settings.AUTH_USER_MODEL, verbose_name='Formateur dépositaire')),
            ],
            options={
                'verbose_name': 'Ressource pédagogique',
                'verbose_name_plural': 'Ressources pédagogiques',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
